# Style: Kimbox

[colors]
foreground = "#C2A383"
background = "#221A02"
cursor_fg = "#221A02"
cursor_bg = "#F79A32"
cursor_border = "#F79A32"
selection_fg = "#221A02"
selection_bg = "#889B4A"

scrollbar_thumb = "#9E7682"
split = "#4C96A8"

ansi = [
  "#201F1F",
  "#DC3958",
  "#819C3B",
  "#F79A32",
  "#733E8B",
  "#7E5053",
  "#088649",
  "#A89983",
]
brights = [
  "#676767",
  "#F14A68",
  "#A3B95A",
  "#F79A32",
  "#DC3958",
  "#FE8019",
  "#4C96A8",
  "#51412C",
]

compose_cursor = "#DC3958"
copy_mode_active_highlight_bg = { Color = "#FF5D62" }
copy_mode_active_highlight_fg = { Color = "#221A02" }
quick_select_label_bg = { Color = "#221A02" }
quick_select_label_fg = { Color = "#A25BC4" }

# If you want extra
[colors.indexed]
16 = "#FFA066"
17 = "#FF5D62"
18 = "#89B482"
19 = "#D3869B"
20 = "#719190"
21 = "#957FB8"
22 = "#938AA9"
23 = "#EA6962"
24 = "#E46876"
25 = "#418292"
26 = "#2AB074"
27 = "#CC6666"
28 = "#77A172"
29 = "#83A598"
30 = "#7E9CD8"
31 = "#BD798B"
32 = "#E78A4E"
33 = "#7E602C"
34 = "#A89984"
35 = "#625A5A"
36 = "#39260E"
37 = "#362712"
38 = "#291804"
39 = "#5E452B"
40 = "#E8C097"
41 = "#665C54"
42 = "#D9AE80"
43 = "#7DAEA3"
44 = "#F79A32"
45 = "#F06431"
46 = "#C2A383"
47 = "#A25BC4"
48 = "#FF5813"
49 = "#A83232"
50 = "#989719"
51 = "#98676A"
52 = "#A06469"
53 = "#A3B95A"
54 = "#A0936A"
55 = "#221A02"
56 = "#689D6A"
57 = "#88C0D0"
58 = "#4F3552"
59 = "#945EB8"
60 = "#BB80B3"
61 = "#AF85A0"
62 = "#D484FF"
63 = "#7E82CC"
64 = "#B279A7"
65 = "#8E77B3"
66 = "#A43A57"
67 = "#EC5F91"
68 = "#FF747C"
69 = "#586081"
70 = "#9A5534"
71 = "#79491d"
72 = "#621A3C"
73 = "#311D55"
74 = "#471337"
75 = "#445321"
76 = "#961134"
77 = "#543739"
78 = "#325C59"
79 = "#7EB2B1"
80 = "#EF1D55"
81 = "#FF9500"
82 = "#819C3B"
83 = "#088649"
84 = "#733E8B"
85 = "#A76C8C"
86 = "#F14A68"
87 = "#DC3958"
88 = "#FE8019"
89 = "#A4B494"
90 = "#95570f"
91 = "#9E7682"
92 = "#B76C77"

[colors.tab_bar]
background = "#221a02"

[colors.tab_bar.active_tab]
bg_color = "#362712"
fg_color = "#E8C097"
intensity = "Bold"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "#291804"
fg_color = "#665C54"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#291804"
fg_color = "#B76C77"
italic = false

[colors.tab_bar.new_tab_hover]
bg_color = "#291804"
fg_color = "#938AA9" # #9E7682
italic = false

[colors.tab_bar.new_tab]
bg_color = "#291804"
fg_color = "#89B482"
